pub const RED_BAR: &str = "bg-red-500 w-16 h-2 rounded-md";
pub const HEADER: &str = "text-4xl font-bold";
pub const DEFAULT_C4_ROWS: usize = 6;
pub const DEFAULT_C4_COLS: usize = 7;
pub const DEFAULT_OT_ROWS: usize = 4;
pub const DEFAULT_OT_COLS: usize = 6;
pub const USER: usize = 1;
pub const COMPUTER: usize = 2;
pub const EMPTY: usize = 0;
